version: '3.3'
services:
  analyze_module:
    image: analyze_module:latest
    volumes:
      - ./analyze_module
  #    networks:
  #      - #TODO

  controller_module:
    image: controller_module:latest
    volumes:
      - ./controller_module
  #    networks:
  #      - #TODO

  password_module:
    image: password_module:latest
    volumes:
      - ./password_module
  #    networks:
  #      - #TODO

  message_broker:
    image: rabbitmq:3-management

volumes:
# networks:
#   -  #TODO
