version: '3.3'
services:
  analyze_module:
    image: analyze_module:latest
    volumes:
      - ./theHarvester:/theHarvester
    networks:
      - front
    depends_on:
      - controller_module
    restart: on-failure

  password_module:
    image: password_module:latest
    volumes:
      - ./theHarvester:/theHarvester
    networks:
      - middle
    depends_on:
      - controller_module
    restart: on-failure

  controller_module:
    image: controller_module:latest
    volumes:
      - ./controller_module_data:/data
    expose:
      - 5672
    networks:
      - back
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '5672']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  theHarvester:
  controller_module_data:

networks:
  front:
  back:
  middle:
