version: '3.3'
services:
  analyze:
    image: analyze:latest
    env_file: .env
    volumes:
      - ./theHarvester:/theHarvester
    networks:
      - analyze-net
    depends_on:
      - controller
    restart: on-failure

  password:
    image: password:latest
    env_file: .env
    volumes:
      - ./theHarvester:/theHarvester
    networks:
      - password-net
    depends_on:
      - controller
    restart: on-failure

  controller:
    image: controller:latest
    env_file: .env
    volumes:
      - ./controller_data:/data
    expose:
      - 5672
    networks:
      - controller-net
    healthcheck:
      test: [ 'CMD', 'nc', '-z', 'localhost', '5672' ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  theHarvester:
  controller_data:


networks:
  analyze-net:
  password-net:
  controller-net:
