version: '3.3'
services:
  analyze_module:
    image: analyze_module:latest
    volumes:
      - analyze_module_data:/analyze_module
    networks:
      - front

  controller_module:
    image: controller_module:latest
    volumes:
      - controller_module_data:/controller_module
    networks:
      - back

  password_module:
    image: password_module:latest
    volumes:
      - password_module_data:/password_module
    networks:
      - middle

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  analyze_module_data:
  controller_module_data:
  password_module_data:

networks:
  front:
    # external: false
  back:
    # external: false
  middle:
    # external: false
