version: '3.3'
services:
  analyze_module:
    image: analyze_module:latest
    volumes:
      - analyze_module_data:/analyze_module
    networks:
      - front

  controller_module:
    image: controller_module:latest
    volumes:
      - controller_module_data:/controller_module
    networks:
      - back

  password_module:
    image: password_module:latest
    volumes:
      - password_module_data:/password_module
    networks:
      - middle

volumes:
  analyze_module_data:
  controller_module_data:
  password_module_data:

networks:
  front:
  back:
  middle:
